/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaz;

import java.awt.Dimension;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author NanD
 */
public class ImagenDialog extends javax.swing.JDialog {

    /**
     * Creates new form ImagenDialog
     */
    public ImagenDialog(java.awt.Frame parent, boolean modal, String URL) {
        super(parent, modal);
        initComponents();
        
        URL="./awesome.png";//Esto se quita, es de prueba y para que os riais un poco :D
        ImageIcon icon = new ImageIcon(URL);
        int ancho=icon.getIconHeight();
        int alto=icon.getIconWidth();
        setSize(ancho, alto);
        IMAGEN.setSize(alto,ancho);
        IMAGEN.setIcon(icon);
        
    }
        public void getSize(int ancho, int alto){
        setSize(ancho, alto);     
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IMAGEN = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(java.awt.Color.black);

        IMAGEN.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IMAGEN, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IMAGEN, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IMAGEN;
    // End of variables declaration//GEN-END:variables
}
