package interfaz;

import metodos.Metodos;

public class PantallaInicial extends javax.swing.JFrame {

    Metodos metodos = new Metodos();

    public PantallaInicial() {
        initComponents();
        setLocationRelativeTo(null);//abre la ventana en el centro de la pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        menuItemConfiguracion = new javax.swing.JMenuItem();
        menuItemEntrenamientos = new javax.swing.JMenuItem();
        menuItemItinerarios = new javax.swing.JMenuItem();
        menuItemPruebaTabla = new javax.swing.JMenuItem();
        menuItemNuevaConfiguracion = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuItemNuevoEntrenamiento = new javax.swing.JMenuItem();
        menuItemNuevoItinerario = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu3.setText("Consulta");

        menuItemConfiguracion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        menuItemConfiguracion.setText("Configuración");
        menuItemConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConfiguracionActionPerformed(evt);
            }
        });
        jMenu3.add(menuItemConfiguracion);

        menuItemEntrenamientos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        menuItemEntrenamientos.setText("Entrenamientos");
        jMenu3.add(menuItemEntrenamientos);

        menuItemItinerarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        menuItemItinerarios.setText("Itinerarios");
        jMenu3.add(menuItemItinerarios);

        menuItemPruebaTabla.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        menuItemPruebaTabla.setText("**prueba*tabla**");
        menuItemPruebaTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPruebaTablaActionPerformed(evt);
            }
        });
        jMenu3.add(menuItemPruebaTabla);

        jMenuBar1.add(jMenu3);

        menuItemNuevaConfiguracion.setText("Nuevo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Configuración");
        menuItemNuevaConfiguracion.add(jMenuItem1);

        menuItemNuevoEntrenamiento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuItemNuevoEntrenamiento.setText("Entrenamiento");
        menuItemNuevaConfiguracion.add(menuItemNuevoEntrenamiento);

        menuItemNuevoItinerario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuItemNuevoItinerario.setText("Itinerario");
        menuItemNuevaConfiguracion.add(menuItemNuevoItinerario);

        jMenuBar1.add(menuItemNuevaConfiguracion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConfiguracionActionPerformed
        ConfiguracionConsulta configuracion = new ConfiguracionConsulta(this, true, metodos);
        configuracion.setVisible(true);
    }//GEN-LAST:event_menuItemConfiguracionActionPerformed

    private void menuItemPruebaTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPruebaTablaActionPerformed
        PruebaRellenarTabla prueba = new PruebaRellenarTabla(this, true, metodos);
        prueba.setVisible(true);
    }//GEN-LAST:event_menuItemPruebaTablaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PantallaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menuItemConfiguracion;
    private javax.swing.JMenuItem menuItemEntrenamientos;
    private javax.swing.JMenuItem menuItemItinerarios;
    private javax.swing.JMenu menuItemNuevaConfiguracion;
    private javax.swing.JMenuItem menuItemNuevoEntrenamiento;
    private javax.swing.JMenuItem menuItemNuevoItinerario;
    private javax.swing.JMenuItem menuItemPruebaTabla;
    // End of variables declaration//GEN-END:variables
}
